// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/49b1ac6a384fab428e0bad052b47f47ff8306193/rickshaw/index.d.ts
//  declare var Rickshaw: any;
declare module "rickshaw"{
    var x: any;
    export = x;
}